version: '3'

services:

  web:
    # build: .
    image: sevenearths1234/django-simple:latest
    env_file:
      - ".env"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: python /code/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=django
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  redis:
    restart: always
    image: redis:latest
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock